name: Setup Plugin action
description: Prepares the environment for gradle tasks
inputs:
  java-version:
    required: true
    default: "17"
    description: The java version to use
  checkout-submodules:
    required: false
    default: "false"
    description: Whether to checkout Git submodules
# required permissions for junit results:
#    checks: write
#    pull-requests: write
  
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: ${{ inputs.checkout-submodules }}
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Create .gradle dir
      shell: bash
      run: mkdir -p $HOME/.gradle

