name: Build and Test Plugin
description: Build and test a gradle plugin

# required permissions for junit results:
#    checks: write
#    pull-requests: write
  
runs:
  using: composite
  steps:
    - name: Build and test with Gradle
      shell: bash
      run: ./gradlew -PprojectVersion=${{ github.ref_name }} build -s --scan

    - name: Publish Unit Test Results (Linux)
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always() && runner.os == 'Linux'
      with:
        files: build/test-results/test/*.xml

    - name: Publish Unit Test Results (Windows)
      uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2
      if: always() && runner.os == 'Windows'
      with:
        files: build/test-results/test/*.xml

    - name: Publish Unit Test Results (macOS)
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: always() && runner.os == 'macOS'
      with:
        files: build/test-results/test/*.xml  

    - name: Post Build
      shell: bash
      run: rm -f $HOME/.gradle/gradle.properties
