name: Build and Test Plugin
description: Build and test a gradle plugin

# required permissions for junit results:
#    checks: write
#    pull-requests: write
  
runs:
  using: composite
  steps:
    - name: Build and test with Gradle
      shell: bash
      run: ./gradlew build -s --scan
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: build/test-results/test/*.xml
    - name: Post Build
      shell: bash
      run: rm -f $HOME/.gradle/gradle.properties
