name: Release Plugin
description: Build and test a gradle plugin
  
runs:
  using: composite
  steps:
    - name: Run gradle release
      shell: bash
      run: ./gradlew -PrunOnCI=true publishIntershopMvnPublicationToMavenRepository publishPlugins -s
    - name: Post Build
      shell: bash
      run: rm -f $HOME/.gradle/gradle.properties
