name: Build and test plugin

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    environment: CIRelease
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-setup@v1.0
      - name: Build
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-build@v1.0
