name: Test actions

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test 'gradle-plugin-setup'
        uses: ./actions/gradle-plugin-setup/

      - name: Test 'gradle-plugin-build'
        uses: ./actions/gradle-plugin-build/
