name: Update Semantic Versioning
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*"
      - "v*.*.*"
jobs:
  update-semver:
    name: Update Semantic Versioning major/minor tags on release tag push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-update-semver@v1
